micronaut:
    application:
        name: micro-storage
    server:
        port: 8080

ms:
    storage:
        type: fs
        fs:
            path: /tmp/.ms
        purge:
            frequency: 30m
            file: /tmp/.purge
    keygen: uuid
#    keygen: human
    registry:
        location: /tmp/.ms/.registry
